apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: 77ca-34-29-204-90.ngrok-free.app/api:version1
          ports:
            - containerPort: 8080
            